travis:
  secure:
    BINSTAR_TOKEN: hZmAgBr4oE6GsTCdfeSheDOrZ+q0EdGpnoFnv9IHGlbXjPO4FeuaI/6cVs7IV3X2DNdZqjCzlJKQgm3s+rCXaJ3CBCBzivHvA+r3iPIgYnYdGmR8RMIbuk/WK4cNS7RgH+OcQEEOKOS1Sd7dAhyKqZ5sKmrjrGrdu2xBMldFs554NTdSUKo1JBCMpZwTKcgrSyTzJR0a5oSi7oyoMk5pK0nMKNgnsrZI7tYUf+L/IUTYzhyP4LLq6L55yBdeCFcsApWHP4mqn0IFAfGOESUv99aZs64rYOS8BHobQLYkUSVwOQ8yF//GA/ZVs141N7khSVcfW4FeWNY++IJNoY8PHpd9NwXEJfTFOnfWeuVG6UxwW7HCC4SROMg3YNUX/u96D1zz/5Ku8RcAPpJfymrt+Y6/CToKSDXFW2ad7i2dXM6wTBDDknGhf6cHXKzuAomb62Jid8d/4C+BbYrJwRZJYXaXDLtCwOqtiZBQOhEj8Ei2YrmRbZ4LGKyl6XfJfxeT3hs2UArJLGCZi/aYxJQuRwNNCOK1hoXwAnfXdPK+7D1kRR5FDlPDkFOa/E/eZD7zThE2ARMAhAv8IP4pix52+VZzCB+6RFehTe9gZ7nTY5SeLJ9XQgYgxTGCvulJnkp4WOsZN2RqE7CjD6JIk85Y8pTvpHAbW3n7OlAgCtUs+Eg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
